title: Wasteland
author: Yang Chao
email: iyeatse@gmail.com
url: https://blog.moecoder.com
baseurl: ""
description: > # description of the site (multiple lines allowed)
  夜切同学的拖更现场 

permalink: /:slug.html

favicon: "favicon.ico"

timezone: Asia/Shanghai

remote_theme: bradleytaunt/lightspeed

theme_config:
  appearance: "auto"
  back_home_text: ".."
  date_format: "%Y-%m-%d"
  show_description: false

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-target-blank
